#BOOK: PYTHOR FOR DATA SCIENCE - CHAPTER 4

##WHY NUMPY?


NUMPY IS AT LEAST 50X FASTER THAN PYTHON LOOP DOING THE SAME THING.



##SECTION 1 - THE ndarray (n-dimensional array)

Things that define ndarray:

**Shape** - the dimensions of the array. A 1D array of 6 numbers has shape (6,). A 2D array with 3 rows and 4 columns has shape (3,4).
PS.: SHAPE IS ALWAYS A TUPLE

**Dtype** - the data type of every element.

**Data buffer** - the raw block of memory where the values live.

In [1]:
# importing the numpy

import numpy as np

# Creating arrays = the most common ways

a = np.array([1,2,3,4,5])         # from a Python list
b = np.array([1.5, 2.5 , 3.5])    # float64 automatically
c = np.zeros((3,4))               # 3x4 array of zeros (3 rows and 4 columns)
d = np.ones((2,3))                # 2x3 array of ones
e = np.arange(0, 20 ,2)           # like range() but returns array
f = np.linspace(0,1,5)            # 5 evenly spaced values from 0 to 1
g = np.full((2,2), 7)             # 2x2 array filled with 7
h = np.eye(3)                     # 3x3 identity matrix

# Inspecting an array
print(a.shape)  # number of rows and columns (5,)
print(a.dtype)  # data type of the array (int)
print(a.ndim)   #dimensions number
print(a.size)   #total number of elements

(5,)
int64
1
5


###SECTION 1 EXERCICES

###Exercise 1.1 — Create a 4×5 array of zeros, then check its shape, dtype, ndim and size.


In [4]:
zeros = np.zeros((4,5))

print(zeros.shape)
print(zeros.dtype)
print(zeros.ndim)
print(zeros.size)

(4, 5)
float64
2
20


###Exercise 1.2 — Create an array of all even numbers from 2 to 20 using np.arange. Then create the same range using np.linspace

In [19]:
even_numbers = np.arange(2,21,2)
print(even_numbers)

[ 2  4  6  8 10 12 14 16 18 20]


In [20]:
even_numbers_ls = np.linspace(2,20, 10)
even_numbers_ls

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

###Exercise 1.3 — Create this array from a nested list and print its shape:
[[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]]

In [15]:
a = np.array([[10,20,30], [40,50,60], [70,80,90]])

print(a.shape)

(3, 3)


## SECTION 2 - ARITHMETIC AND VECTORIZATION

Core idea of Numpy. No loop required to do any arithmetic operation between two arrays of the same shape.

In [24]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

print(a+b)
print(a*b)
print(b/a)
print(a**2)

[11 22 33 44]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 1  4  9 16]


Scalar Operations broadcast automatically

In [25]:
a = np.array([1,2,3,4])
print(a*2)
print(a+100)
print(a>2)

[2 4 6 8]
[101 102 103 104]
[False False  True  True]


Universal Functions - Math Functions

In [26]:
a = np.array([1.0, 4.0, 9.0, 16.0])

print(np.sqrt(a))
print(np.log(a))                     # natural log of each element
print(np.exp(a))                     # e^x for each element
print(np.abs(np.array([-3,-1,2,4]))) #absolute value

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[3 1 2 4]


###SECTION 2 EXERCICES

Exercise 2.1 — Create two arrays a = [2, 4, 6, 8] and b = [1, 3, 5, 7]. Compute and print: their sum, difference, product, and a divided by b. Do this with no loops.

In [28]:
a = np.array([2,4,6,8])
b = [1,3,5,7]

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 3  7 11 15]
[1 1 1 1]
[ 2 12 30 56]
[2.         1.33333333 1.2        1.14285714]


Exercise 2.2 — Create an array of angles in degrees: [0, 30, 45, 60, 90]. Convert them to radians (multiply by np.pi / 180), then apply np.sin() to all of them at once. Round to 2 decimal places with .round(2).

In [32]:
angles_degrees = np.array([0,30,45,60,90])
radians = np.sin(angles_degrees * (np.pi/180)).round(2)

print(radians)

[0.   0.5  0.71 0.87 1.  ]
